name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
          cache: 'maven'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw verify

      # Step 4: Build Docker image and push it if on the main branch
      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          # Build Docker image using Spring Boot's build-image goal
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/bookmarker-api

          # Login to Docker Hub with secrets
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

          # Push the Docker image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
