name: Build

on:
  push:
    branches: [ "**" ]  # Trigger for all branches

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw  # Ensure the mvnw script is executable

      - name: Build with Maven
        run: ./mvnw -ntp verify # Build the project with Maven

      - name: Debug Docker Secrets (TEMP)
        run: |
          echo "Username is: '${{ secrets.DOCKER_USERNAME }}'"
          echo "Password length: $(echo '${{ secrets.DOCKER_PASSWORD }}' | wc -c)"

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKER_USERNAME }}/bookmarker-api
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
